# Generated by Django 5.1.7 on 2025-03-28 11:02

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CreatePdf",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("pdf", models.URLField(default="", max_length=400)),
                ("dept", models.CharField(default="", max_length=50)),
                ("session", models.CharField(default="", max_length=50)),
                ("course_title", models.CharField(default="", max_length=200)),
                ("teacher", models.CharField(default="", max_length=100)),
                ("contributor", models.CharField(default="", max_length=50)),
                ("is_approved", models.BooleanField(default=False)),
                ("time", models.DateField(auto_now_add=True)),
            ],
        ),
    ]
