# Generated by Django 5.1.7 on 2025-04-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Core", "0002_alter_createpdf_pdf"),
    ]

    operations = [
        migrations.AddField(
            model_name="createpdf",
            name="semester",
            field=models.CharField(default="", max_length=50),
        ),
    ]
